async function run() {
  try {
  } catch (err: any) {
    console.log({
      message: err.message,
      name: err.name
    })
  }
}

run()
